
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 11 10:44:55 VET 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OVER = 17;
  public static final int GE = 33;
  public static final int LPAREN = 18;
  public static final int SEMI = 20;
  public static final int REPEAT = 6;
  public static final int INT = 21;
  public static final int FOR = 23;
  public static final int MINUS = 15;
  public static final int WRITE = 9;
  public static final int RPAREN = 19;
  public static final int OBRACKET = 25;
  public static final int AND = 27;
  public static final int LT = 30;
  public static final int CBRACKET = 26;
  public static final int OR = 28;
  public static final int BEGIN = 36;
  public static final int UNTIL = 7;
  public static final int NUM = 11;
  public static final int PLUS = 14;
  public static final int ASSIGN = 12;
  public static final int IF = 2;
  public static final int ID = 10;
  public static final int LE = 32;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int COMA = 24;
  public static final int VOID = 22;
  public static final int EQ = 13;
  public static final int TIMES = 16;
  public static final int ELSE = 4;
  public static final int READ = 8;
  public static final int NEQUAL = 29;
  public static final int THEN = 3;
  public static final int END = 5;
  public static final int FALSE = 38;
  public static final int GT = 31;
}

